<a href="https://colab.research.google.com/github/GOD-DEBANG/AI_ML/blob/main/Copy_of_Untitled0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Numpy arrays


import numpy as np

np.array([1,2,3,4,5,6,7,8,9,10])


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.array([1,2,3,4,5,6,7,8,9,10])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
a = [1,2,3,4,5,6,7,8,9,10,"Hello"]
print(a)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 'Hello']


In [ ]:
np.array(a)

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'Hello'],
      dtype='<U21')

In [ ]:
l = [[1,2,3],[4,5,6],[7,8,9]]
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# Array Generation

arr1 = np.arange(1,11,2)
arr1

array([1, 3, 5, 7, 9])

In [ ]:
arr2 = np.zeros(10)
arr2

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
arr3 = np.zeros((4,8))
arr3

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
arr4 = np.linspace(0,1,100)
arr4

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [ ]:
# Random generation function

np.random.rand(10)

array([0.33213259, 0.58253318, 0.60032971, 0.75828103, 0.26436069,
       0.84781512, 0.49813717, 0.25006452, 0.87674478, 0.77105038])

In [ ]:
np.random.randn(10)

array([-1.619856  ,  0.57899837, -0.9454078 ,  1.42378984,  0.57692509,
        0.48543527,  0.28698148, -1.79749024,  1.96495361,  0.24563754])

In [ ]:
np.random.randint(10,20,100)

array([11, 17, 16, 15, 16, 14, 13, 16, 17, 14, 19, 12, 16, 17, 15, 11, 10,
       18, 11, 15, 15, 16, 17, 18, 16, 14, 18, 19, 15, 16, 19, 11, 14, 11,
       16, 11, 19, 13, 18, 18, 15, 10, 15, 11, 12, 11, 10, 13, 19, 18, 17,
       19, 17, 11, 13, 15, 15, 10, 13, 10, 19, 17, 16, 18, 10, 12, 11, 13,
       13, 11, 11, 17, 17, 14, 18, 18, 12, 16, 16, 13, 16, 16, 16, 17, 16,
       14, 18, 11, 18, 15, 13, 12, 14, 17, 19, 15, 17, 14, 15, 15])